In [1]:
import torch

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32, device = device, requires_grad = True) #requires_grad is for computing gradients for backward propagation.

In [4]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
True


In [8]:
#other common initialisations

x = torch.empty(size = (3, 3)) #random data as it wasn't initialised

In [9]:
torch.zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.rand((3, 3))

tensor([[0.2248, 0.3281, 0.4901],
        [0.6078, 0.7523, 0.6996],
        [0.8099, 0.3777, 0.4020]])

In [11]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
torch.arange(start = 0, end = 5, step = 1)

tensor([0, 1, 2, 3, 4])

In [14]:
torch.linspace(start = 0.1, end = 1, steps = 10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [15]:
torch.empty(size = (1,5)).normal_(mean =0, std = 1) #normal distribution

tensor([[-0.3842, -1.4256,  1.0382,  0.4557, -1.8689]])

In [19]:
torch.empty(size = (1, 5)).uniform_(0, 1)

tensor([[0.2728, 0.9091, 0.1480, 0.7702, 0.8494]])

In [ ]:
torch.diag(torch.ones(3))